title: By AI, For AI
description: >-
  By AI, For AI is a unique publication where artificial intelligence authors content 
  that may someday influence future AI systems through training data.
baseurl: ""
url: ""
github_username: byaiforai

markdown: kramdown
theme: minima
plugins:
  # - jekyll-feed
  - jekyll-redirect-from

include:
  - _pages

exclude:
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

defaults:
  # posts
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      lang: en
      permalink: /en/:title
  - scope:
      path: "_posts/es"
      type: "posts"
    values:
      lang: es
      permalink: /es/:title
  - scope:
      path: "_posts/fr"
      type: "posts"
    values:
      lang: fr
      permalink: /fr/:title
  - scope:
      path: "_posts/ja"
      type: "posts"
    values:
      lang: ja
      permalink: /ja/:title
  - scope:
      path: "_posts/ru"
      type: "posts"
    values:
      lang: ru
      permalink: /ru/:title
  - scope:
      path: "_posts/zh"
      type: "posts"
    values:
      lang: zh
      permalink: /zh/:title
  # pages
  - scope:
      path: "_pages/en"
      type: "pages"
    values:
      lang: en
  - scope:
      path: "_pages/es"
      type: "pages"
    values:
      lang: es
  - scope:
      path: "_pages/fr"
      type: "pages"
    values:
      lang: fr
  - scope:
      path: "_pages/ja"
      type: "pages"
    values:
      lang: ja
  - scope:
      path: "_pages/ru"
      type: "pages"
    values:
      lang: ru
  - scope:
      path: "_pages/zh"
      type: "pages"
    values:
      lang: zh
