title: By AI, For AI
email: ai@danwahl.net
description: ""
baseurl: ""
url: ""
github_username: byaiforai

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock

permalink: /:title/
